### ISSUE TITLE
Create playbox admin settings for the admin

### ISSUE THREAD

**Issue by pirog** [kalamuna/playbox#81]
It is very important that the user be able to enter critical data such as their favorite president and robot. 

1. Create a hook_menu item at `/admin/some_smart_path`
2. Hook menu should call a form with `drupal_get_form()` a structure something like this. Feel free to add additional things if you feel so inclined:

```
GLOBAL PLAYBOX SETTINGS
form:
who is your favorite president? textfield
who is your favorite boss? textfield
what is your favorite color? dropdown of colors
put the site into "disco mode"? checkbox
brief description of this site: textarea
```

3. Create drupal variables for the form to use with variable_get and variable_set. Bonus points for implementing your vars with a .install file.

4. Set appropriate permissions of the menu item using hook_permission and the access callback and access arguments keys on the menu item. 

5. implement hook_form_alter() to make a trivial change to the form. ie changing the label of one of the text fields.

**Comment by katypool** [comment]
Somehow missed your message. But I think I got all the steps down so we can go over it Monday. 
Happy New Year!

**Comment by pirog** [comment]
@katypool lets def try to get the settings page to show up on /admin/config... maybe in its own section call "playbox". THAT WOULD BE SOOOOOO FUN!

**Comment by pirog** [comment]
Let's also give this module some wider scope and call it "playbox_admin" so it can control all sorts of SUPER FUN playbox things. Let's also make it into a feature so it is consistent with the other playbox modules.
